apiVersion: v1  #Defines the API Version
kind: Service   #Kinds parameter defines which kind of file is it, over here it is Service
metadata:
    name: netsvc   #Stores the name of the service
spec:            # Under Specifications, you mention all the specifications for the service
  type: NodePort
  selector:
    app: httpd
  ports:
  - protocol: TCP
    port: 82
    targetPort: 8085    #Target Port number is 8084